#!/usr/bin/env groovy
// This will donwload the common Jenkins Job
// To modify the Job, update the DevOpsroject.groovy
// DO NOT EDIT THIS FILE
@Library('CLib@master') _
def common = new CommonBuildPipeline()
common.runPipeline()
